### ISSUE TITLE
A error in Ubuntu running  by conda

### ISSUE THREAD

**Issue by hannet91** [allind/EukDetect#10]
Hi, 

I got a error in running Eukdetect by linux, the error report as following:

03/07/2021 17:57:15:  Parsing config file ...
03/07/2021 17:57:15:  Error: missing files in database directory: all_buscos_v4.fna.1.bt2, all_buscos_v4.fna.2.bt2, all_buscos_v4.fna.3.bt2, all_buscos_v4.fna.4.bt2, all_buscos_v4.fna.rev.1.bt2, all_buscos_v4.fna.rev.2.bt2

I am used the 1.2 version and newest database, could you tell me how to fix this question. Thanks!

Liao

**Comment by allind** [comment]
Thanks for reaching out. Could you post the contents of your config file? I suspect you have the wrong database prefix in the config file - you likely need to change it to "ncbi_eukprot_met_arch_markers.fna".

**Comment by hannet91** [comment]
Thanks. I have fixed this error by replaced the prefix as your suggestion. 
But a new error come as following:
(eukdetect) [liaohp@ubuntu EukDetect-1.2] /data/software/EukDetect-1.2
$eukdetect --mode runall --configfile compost_configfile.yml  --cores 60 
03/09/2021 09:05:05:  Parsing config file ...
Traceback (most recent call last):
  File "/data/software/conda2/envs/eukdetect/bin/eukdetect", line 33, in <module>
    sys.exit(load_entry_point('EukDetect==1.0.1', 'console_scripts', 'eukdetect')())
  File "/data/software/conda2/envs/eukdetect/lib/python3.6/site-packages/EukDetect-1.0.1-py3.6.egg/eukdetect/runall.py", line 136, in main
  File "/data/software/conda2/envs/eukdetect/lib/python3.6/site-packages/EukDetect-1.0.1-py3.6.egg/eukdetect/runall.py", line 365, in check_aln_output
AttributeError: 'str' object has no attribute 'keys'

the confile file as below：

#Default config file for eukdetect. Copy and edit for analysis

#Directory where EukDetect output should be written
output_dir: "/data/software/EukDetect-1.2/output"
  
#Indicate whether reads are paired (true) or single (false)
paired_end: true 

#filename excluding sample name. no need to edit if paired_end = false
fwd_suffix: "_1.fastq.gz" 

#filename excludign sample name. no need to edit if paired_end = false
rev_suffix: "_2.fastq.gz"

#file name excluding sample name. no need to edit if paired_end = true 
se_suffix: ".fastq.gz" 

#length of your reads. pre-trimming reads not recommended
readlen: 125

#full path to directory with raw fastq files
fq_dir: "/data/liaohp/project1/Clean_data/clean_data/"

#full path to folder with eukdetect database files
database_dir: "/data/database/eukdb/"

#name of database. Default is original genomes only database name
database_prefix: "ncbi_eukprot_met_arch_markers.fna"

#full path to eukdetect installation folder
eukdetect_dir: "/data/software/EukDetect-1.2"

#list sample names here. fastqs must correspond to {samplename}{se_suffix} for SE reads or {samplename}{fwd_suffix} and {samplename}{rev_suffix} for PE
#each sample name should be preceded by 2 spaces and followed by a colon character
samples:
  sample1:H0-1_clean
  sample2:H0-2_clean

**Comment by allind** [comment]
This is coming from an issue in your config file. Assuming your read files are titled "H0-1_clean_1.fastq.gz" and similar, the sample section should look like this:

```
samples:
  H0-1_clean:
  H0-2_clean
```

Let me know if that addresses the issue.

**Comment by hannet91** [comment]
Thanks for help. It can work.
