### ISSUE TITLE
Error not allowing for analysis of single reads (not paired end)

### ISSUE THREAD

**Issue by SethCommichaux** [allind/EukDetect#14]
When I try to analyze single end reads (not paired end) I get the following error:

**Command:** eukdetect --mode runall --configfile default_configfile.yml --cores 12

04/09/2021 12:57:22:  Parsing config file ...

Traceback (most recent call last):
  File "/hpc/scratch/Seth.Commichaux/envs/eukdetect/bin/eukdetect", line 33, in <module>
    sys.exit(load_entry_point('EukDetect==1.0.1', 'console_scripts', 'eukdetect')())
  File "/hpc/scratch/Seth.Commichaux/envs/eukdetect/lib/python3.6/site-packages/EukDetect-1.0.1-py3.6.egg/eukdetect/runall.py", line 139, in main
  File "/hpc/scratch/Seth.Commichaux/envs/eukdetect/lib/python3.6/site-packages/EukDetect-1.0.1-py3.6.egg/eukdetect/runall.py", line 500, in check_readlen
UnboundLocalError: local variable 'fwd' referenced before assignment

Here is what the config file looks like:

#Default config file for eukdetect. Copy and edit for analysis

#Directory where EukDetect output should be written
output_dir:  "/hpc/scratch/Seth.Commichaux/simulated/eukdetect_virus"

#Indicate whether reads are paired (true) or single (false)
paired_end:  false

#file name excluding sample name. no need to edit if paired_end = true
se_suffix:  ".fastq"

#length of your reads. pre-trimming reads not recommended
readlen:  150

#full path to directory with raw fastq files
fq_dir:  "/hpc/scratch/Seth.Commichaux/simulated"

#full path to folder with eukdetect database files
database_dir:  "/hpc/scratch/Seth.Commichaux/tool/EukDetect/eukdb"

#name of database. Default is original genomes only database name
database_prefix:  "ncbi_eukprot_met_arch_markers.fna"

#full path to eukdetect installation folder
eukdetect_dir:  "/hpc/scratch/Seth.Commichaux/tool/EukDetect"

#list sample names here. fastqs must correspond to {samplename}{se_suffix} for SE reads or {samplename}{fwd_suffix} and {samplename}{rev_suffix} for PE
#each sample name should be preceded by 2 spaces and followed by a colon character
samples:
  virus:

**Comment by allind** [comment]
There was an error causing this - it should be fixed now. Can you update to the latest github version, reinstall, and see if your issue is resolved? Thanks.

**Comment by SethCommichaux** [comment]
I was able to reinstall and to clear the previous error, but now I get this new error.

**command: ** eukdetect --mode runall --configfile default_configfile.yml --cores 12

04/09/2021 14:34:27:  Parsing config file ...
04/09/2021 14:34:28:  Running: snakemake --snakefile /hpc/scratch/Seth.Commichaux/tool/EukDetect/rules/eukdetect.rules --configfile default_configfile.yml --cores 12
04/09/2021 14:34:28:  Redirecting snakemake output to snakemake_1617993268.135897.log
04/09/2021 14:34:28:  Snakemake finished
04/09/2021 14:34:28:  Something went wrong with snakemake. Check log files

**Command:** cat snakemake_1617993268.135897.log

Building DAG of jobs...
MissingInputException in line 156 of /hpc/scratch/Seth.Commichaux/tool/EukDetect/rules/eukdetect.rules:
Missing input files for rule countreads:
/hpc/scratch/Seth.Commichaux/tool/EukDetect/eukdetect/bam_to_pid.py

**Comment by allind** [comment]
It looks like snakemake isn't detecting the file ``bam_to_pid.py`` in the ``/hpc/scratch/Seth.Commichaux/tool/EukDetect/eukdetect/`` folder. If you have eukdetect installed in ``/hpc/scratch/Seth.Commichaux/tool/EukDetect`` that should be working but something's gone wrong. Can you check the contents of ``/hpc/scratch/Seth.Commichaux/tool/EukDetect/eukdetect/``?

**Comment by SethCommichaux** [comment]
Oops, my mistake! It runs to completion now. Thanks so much for your prompt response :-)
