### ISSUE TITLE
error estimating library size for single reads?

### ISSUE THREAD

**Issue by SethCommichaux** [allind/EukDetect#15]
Hello,

I'm running eukdetect for single-end reads, but am getting the following error which doesn't make sense because there shouldn't be a library size for single-end reads.

'[markdup] warning: unable to calculate estimated library size. Read pairs 0 should be greater than duplicate pairs 0, which should both be non zero.'

The config file looks like this:

#Directory where EukDetect output should be written
output_dir:  "/hpc/scratch/Seth.Commichaux/samples/eukdetect/"

#length of your reads. pre-trimming reads not recommended
readlen: 150

#Indicate whether reads are paired (true) or single (false)
paired_end:  false

#file name excluding sample name. no need to edit if paired_end = true
se_suffix:  ".fastq"

#full path to directory with raw fastq files
fq_dir:  "/hpc/scratch/Seth.Commichaux/samples/"

#full path to folder with eukdetect database files
database_dir:  "/hpc/scratch/Seth.Commichaux/EukDetect/eukdb/"

#name of database. Default is original genomes only database name
database_prefix:  "ncbi_eukprot_met_arch_markers.fna"

#full path to eukdetect installation folder
eukdetect_dir:  "/hpc/scratch/Seth.Commichaux/EukDetect/"

#list sample names here. fastqs must correspond to {samplename}{se_suffix} for SE reads or {samplename}{fwd_suffix} and {samplename}{rev_suffix} for PE
#each sample name should be preceded by 2 spaces and followed by a colon character
samples:
  sample1:
  sample2:

**Comment by allind** [comment]
This is a warning coming from the samtools markdup step. Does eukdetect completely fail, or are you getting this warning but the pipeline completes with output files?

**Comment by SethCommichaux** [comment]
Unfortunately eukdetect completely fails. The only output directories are
"aln" and "filtering."

**Comment by SethCommichaux** [comment]
Turns out that the system administrator had changed the configuration of samtools and that was throwing the error. Just had to reinstall and things worked perfectly. Apologies and many thanks!
