### ISSUE TITLE
necessary to filter bac or host at the beginning?

### ISSUE THREAD

**Issue by ifanlyn95** [allind/EukDetect#16]
Hi, Abigail Lind. If I want to utilize EukDetect to align the raw metagenomic fastQ files containing the host or bacteria sequences. Is it necessary to filter the contamination at the beginning?

**Comment by ifanlyn95** [comment]
Thank you for your works and looking for your replying.
If my publication has been published, I would like to cite you.

**Comment by allind** [comment]
It depends on what the host is. If the host is a vertebrate animal such as human or a land plant, it's probably not necessary. If the host is something else, it might be contained in the database ot have a closely related species in the database, so I would recommend prefiltering

This work has been published - thanks for your interest. Please cite this paper: https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-021-01015-y

**Comment by ifanlyn95** [comment]
Received, I will check it and follow your suggestions.
thank you very much.
