### ISSUE TITLE
Is this package still being maintained and/or supported? 

### ISSUE THREAD

**Issue by antgonza** [allind/EukDetect#22]
Hello,

Just want to be sure that is worth to continue using this tool, fine if not. 

Anyway, looking at the last time there was:
- a release: https://github.com/allind/EukDetect/releases ~12 months
- a commit to master: https://github.com/allind/EukDetect/commits/master ~11 months
- a reply from the developers in an open issue: https://github.com/allind/EukDetect/issues/13#issuecomment-921081213 ~6 months 
it makes me wonder if there is any support available.

Thank you.

**Comment by djkt604** [comment]
Thanks fo your interest in using EukDetect. The developer is on parental leave, so please accept our lab's apologies for delays in responding to queries. The package is indeed still being maintained and supported, just with a 3 month break.  Best, Katie Pollard
