### ISSUE TITLE
Combining results from multiple samples

### ISSUE THREAD

**Issue by bhandari63** [allind/EukDetect#26]
With the updated database and scripts, I was able to get the relative abundance (Sample1_filtered_hits_eukfrac.txt) of different eukaryotes in my metagenome samples. What is the best way to combine my results from different samples ( I have 60 samples) into one so I can use various visualization tools?

**Comment by allind** [comment]
Check out the newly added ```combine_rpks_eukfrac.py``` script in the ```eukdetect/``` directory. Please reach out with any questions or issues.
