### ISSUE TITLE
EukDetect recent database

### ISSUE THREAD

**Issue by magibc** [allind/EukDetect#28]
Hi developers and first of all I would like to congratulate your work because your tool I think will help me a lot in my metagenomic shotgun analysis. 

Prior to install, I have gone to the figshare to download the most recent database : https://figshare.com/articles/dataset/Eukdetect_database/12670856/8

Nevertheless, I found two versions of the same day (23/04/2022) but one version (version 8) is of double size than version 9. It's more complete the release 8 I suppose, not?

Thanks on advance,

Kind regards,

Maggie.

**Comment by allind** [comment]
Hey, thanks for your interest and thanks for reaching out. Version 9 is the correct one - version 8 has some unnecessary files which is why it's so much larger.

**Comment by magibc** [comment]
Thanks
