### ISSUE TITLE
How to calculate the abundance of eukaryotic and prokaryotic microorganisms in the same sample

### ISSUE THREAD

**Issue by alienn233** [allind/EukDetect#29]
I want to use eukdetect and metaphlan2 together
Is this reasonable?

**Comment by allind** [comment]
This is fine, but they'll be separate analyses since they're each calculating abundances separately of each other.

**Comment by alienn233** [comment]
> This is fine, but they'll be separate analyses since they're each calculating abundances separately of each other.
I noticed that the result of EukDetect is absolute abundance. How to calculate the relative abundance?
