### ISSUE TITLE
Empty read count file. Likely no aligned reads in sample

### ISSUE THREAD

**Issue by Liuyuxinn** [allind/EukDetect#39]
Hello

To identify eukaryotic species that may be present in the metagenomics sequenced in my study , I ran the program EukDetect (--mode runall) on all metagenomes sequenced (clean reads) in this study. 

However,the output file (filtered_hits_eukfrac.txt; filtered_hits_table.txt) of some sample showed:
 "Empty read count file. Likely no aligned reads in sample."

I'm so confused, is this normal?
And what does this means?

Could you help me? thanks a million!

**Comment by allind** [comment]
Thanks for reaching out. This means that there are no sequencing reads that align to the eukdetect database, which means that there either aren't eukaryotes detectable by eukdetect in your sample or they weren't captured with the sequencing you did. Hope that helps.
