### ISSUE TITLE
finding installation folder on a cluster

### ISSUE THREAD

**Issue by iholmes** [allind/EukDetect#43]
Hi! I am trying to run eukdetect on my university's computer cluster. I am not sure what path to give for 'full path to eukdetect installation folder' in the config file. I tried '/programs/miniconda3/envs/eukdetect' at the cluster admin's suggestion, but got the error message 'Error: could not find /rules/eukdetect_eukfrac.rules in eukdetect_dir specified in configfile.' What would you suggest? Thank you!

**Comment by allind** [comment]
The correct folder is the one where you download the github repo and install eukdetect - not the conda environment, which is what you're currently specifying. On a cluster, you can probably do this in your home directory.
