### ISSUE TITLE
Fastq PAIRED Doubt 

### ISSUE THREAD

**Issue by sarpiens** [allind/EukDetect#46]
Hi, I have a question about how the Fastq PAIRED files are handled internally by the pipeline. Specifically, I was wondering if it takes into account cases where you can have identical read headers in R1 and R2 files.
Exem1:
R1 File: Sample1.1
R2 File: Sample1.1
Exem2:
R1 File: Sample1.1 /1
R2 File: Sample1.1 /2

Would the result be equivalent in Exem1 and Exem2?
Thank you very much in advance.
Regards

**Comment by allind** [comment]
Hi, thanks for reaching out with your question. The part of the eukdetect pipeline that deals with paired end reads is bowtie2.  My understanding of how bowtie2 works is that these files are treated separately and it should produce the same result, however, if this is not the case, this is an issue that would need to be brought to the attention of the bowtie2 developers.
