### ISSUE TITLE
Error in config file

### ISSUE THREAD

**Issue by arfaiq** [allind/EukDetect#47]
Hi,

Thank you for developing EukDetect. It looks very promising!

I installed the tool and ran a test. The test worked fine. 

However, when trying to run EukDetect, I receive the following error: 

yaml.scanner.ScannerError: mapping values are not allowed here
in "./eukdetect_configfile.yml", line 36, column 24

My config file looks like this: 
#Default config file for eukdetect. Copy and edit for analysis

#Directory where EukDetect output should be written
output_dir: "/cluster/projects/nn9383k/arfa/eukdetect/EukDetect/eukdetect1/output"

#Indicate whether reads are paired (true) or single (false)
paired_end: true

#filename excluding sample name. no need to edit if paired_end = false
fwd_suffix: "_paired1.fq"

#filename excludign sample name. no need to edit if paired_end = false
rev_suffix: "_paired2.fq"

#file name excluding sample name. no need to edit if paired_end = true
se_suffix: ".fastq.gz"

#length of your reads. pre-trimming reads not recommended
readlen: 150

#full path to directory with raw fastq files
fq_dir: "/cluster/projects/nn9383k/arfa/mockcommunity"

#full path to folder with eukdetect database files
database_dir: "/cluster/projects/nn9383k/arfa/eukdetect/EukDetect/eukdb"

#name of database. Default is original genomes only database name
database_prefix: "ncbi_eukprot_met_arch_markers.fna"

#full path to eukdetect installation folder
eukdetect_dir: "/cluster/projects/nn9383k/arfa/eukdetect/EukDetect/eukdetect1"

#list sample names here. fastqs must correspond to {samplename}{se_suffix} for SE reads or {samplename}{fwd_suffix} and {samplename}{rev_suffix} for PE
#each sample name should be preceded by 2 spaces and followed by a colon character
samples:
  sample1:  mock_fungal:
  sample2:  mock_fungal:

I ran a SLURM job script to run this and it seems the job is exiting on "sample1: mock_fungal:" row. 

Any advice?

**Comment by allind** [comment]
Thanks for reaching out. Try reconfiguring the config file as possible:

```
samples:
  mock_fungal:
  mock_fungal:
```

See if that works.

**Comment by arfaiq** [comment]
Hi Abigail,

That seemed to have done the trick! Thank you.
