### ISSUE TITLE
How do you classify the fasta genome

### ISSUE THREAD

**Issue by qkqk-hub** [allind/EukDetect#48]
Hello, can I enter fasta file directly?

I have a eukaryotic genome and I want to classify it.What should I do?

Thank you for your reply!

With best wishes.

**Comment by allind** [comment]
Thanks for reaching out. There are instructions to create your own database [here](https://github.com/allind/EukDetect/blob/master/build_custom_db.md). You can either use just your focal species + a few others, or you can use this to add your species to the full database. Please reach out with any questions - this is newly released and looking for bugs.
