### ISSUE TITLE
Cannot find package: libgfortran-ng==7.5.0=hdf63c60_6

### ISSUE THREAD

**Issue by ginaguzzo** [allind/EukDetect#8]
Hi there, thanks for making this exciting tool! I encountered an issue when creating the conda environment:

```
ResolvePackageNotFound:
    - libgfortran-ng==7.5.0=hdf63c60_6 
```

I found a similar issue [here](https://github.com/bactopia/bactopia/issues/138#issuecomment-694543360), and tried the same solution by editing the line in the ``` environment.yml ``` file from 
``` - libgfortran-ng==7.5.0=hdf63c60_6 ``` to just ``` - libgfortran-ng==7.5.0 ``` so there is no build number.

Seems to be working now but I'll update if I encounter any further errors.

**Comment by allind** [comment]
Thanks for reporting this and your solution! I've updated the environment.yml.
